version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $PWD
      - run: cd ~/ && ls
      - run: cd /usr && ls
      - run: cd src
      - run: echo $PWD
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install OpenCv
          command: 'sudo apt-get install libopencv-dev'
      - run:
          name: Install GTest
          command: 'sudo apt-get install libgtest-dev'
      - run: cd src && cmake .
      - run: cd src && make
      - run: cd src && ./runTests

