version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $PWD
      - run: ls
      - run: cd src
      - run: echo $PWD
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run: ./src/cmake .
      - run: ./src/make
      - run: ./runTests

