version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $PWD
      - run: ls
      - run: cd src
      - run: echo $PWD
      - run: src/cmake .
      - run: src/make
      - run: ./runTests

