version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install OpenCv
          command: 'sudo apt-get install libopencv-dev'
      - run:
          name: Install GTest
          command: 'sudo apt-get install libgtest-dev'
      - run:
          name: Install Valgrind 
          command: 'sudo apt install valgrind'
      - run: cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv /usr/src/gtest/*.a /usr/lib/
      - run: cd src && cmake . && make
      - run: cd src && valgrind --leak-check=full ./runTests

