version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $PWD
      - run: ls
      - run: cd src
      - run: echo $PWD
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run: cd src && cmake .
      - run: cd src && make
      - run: cd src && ./runTests

